<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>diffbot_nodes</name>
  <version>0.1.0</version>
  <description>ROS 2 nodes for the diffbot differential-drive robot. (Unit 1)</description>
  <maintainer email="a.pahlevani1998@gmail.com">Ali Pahlevani</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <!-- This line is what makes colcon build the library first (Unit 1, slide 73) -->
  <depend>diffbot_kinematics</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
